server:
  port: 8080

spring:
  application:
    name: mechanic-buddy-backend

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/mechanic_buddy_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root # Replace with your local MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
